---
# tasks file for vxlan_evpn_fabric

- name: Enable and set DCI interfaces in L3 mode. Ensure jumbo MTU.
  # noqa no-loop-var-prefix
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.name }}"
        mode: layer3
        enabled: true
        mtu: "{{ mtu }}"
    state: merged
  loop: "{{ dci_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  notify: Save nxos

- name: Ensure medium p2p for DCI interfacs.
  # noqa no-loop-var-prefix
  cisco.nxos.nxos_config:
    lines:
      - medium p2p
    parents:
      - interface {{ item.name }}
  loop: "{{ dci_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  notify: Save nxos

- name: Assign IP address to DCI interfaces.
  # noqa no-loop-var-prefix
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.name }}"
        ipv4:
          - address: "{{ item.ip }}/31"
            tag: "{{ rmap_redist_direct_tag }}"
    state: merged
  loop: "{{ dci_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  notify: Save nxos

- name: Configure remote border-leafs as neighbors under BGP process.
  # noqa no-loop-var-prefix
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ bgp_asn }}"
      router_id: "{{ rid_ip }}"
      neighbors:
        - neighbor_address: "{{ item.bgp_neighbor_ip }}"
          remote_as: "{{ item.bgp_remote_asn }}"
          description: "{{ item.bgp_neighbor_name }}"
          update_source: "{{ item.name }}"
    state: merged
  loop: "{{ dci_interfaces }}"
  loop_control:
    label: BGP neighbor {{ item.bgp_neighbor_name }}
  notify: Save nxos

- name: Set address-family to IPv4-unicast for border-leaf neighbors under BGP process.
  # noqa no-loop-var-prefix
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config:
      as_number: "{{ bgp_asn }}"
      neighbors:
        - neighbor_address: "{{ item.bgp_neighbor_ip }}"
          address_family:
            - afi: ipv4
              safi: unicast
    state: merged
  loop: "{{ dci_interfaces }}"
  loop_control:
    label: BGP neighbor {{ item.bgp_neighbor_name }}
  notify: Save nxos

- name: Create route-map for redistribution of directly connected routes.
  cisco.nxos.nxos_route_maps:
    config:
      - route_map: "{{ rmap_redist_direct_name }}"
        entries:
          - sequence: 10
            action: permit
            match:
              tags: "{{ rmap_redist_direct_tag }}"
    state: merged
  notify: Save nxos

- name: Redistribute route-map in IPv4 address-family under BGP. Enable forwarding over multiple paths.
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ bgp_asn }}"
      address_family:
        - afi: ipv4
          safi: unicast
          maximum_paths:
            parallel_paths: 4
          redistribute:
            - protocol: direct
              route_map: "{{ rmap_redist_direct_name }}"
    state: merged
  notify: Save nxos
