---
# tasks file for vxlan_evpn_fabric

- name: Set multisite ID for fabric. Ensure delay-restore is 300 seconds.
  cisco.nxos.nxos_config:
    lines:
      - delay-restore time 300
    parents:
      - evpn multisite border-gateway {{ bgp_asn }}
  notify: Save nxos

- name: Add multisite VIP VTEP loopback to NVE-interface.
  cisco.nxos.nxos_vxlan_vtep:
    interface: nve1
    multisite_border_gateway_interface: "{{ loopback_dci }}"
    state: present
  notify: Save nxos

- name: Configure remote border-leafs as neighbors. Ensure peer-type is fabric-external. Increase ttl for eBGP.  # since using loopback as source.
  # noqa loop-var-prefix
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ bgp_asn }}"
      router_id: "{{ rid_ip }}"
      neighbors:
        - neighbor_address: "{{ hostvars[item]['rid_ip'] }}"
          remote_as: "{{ hostvars[item]['bgp_asn'] }}"
          description: "{{ hostvars[item]['inventory_hostname'] }}"
          update_source: "{{ loopback_rid }}"
          peer_type: fabric-external
          ebgp_multihop: 2
    state: merged
  when:
    - hostvars[item]['network_function'] == 'border-leaf'
    - hostvars[item]['bgp_asn'] != bgp_asn
  loop: "{{ bgp_neighbors }}"
  loop_control:
    label: BGP neighbor {{ hostvars[item]['inventory_hostname'] }}
  notify: Save nxos

- name: Configure EVPN address-family for BGP neighbors.
  # noqa loop-var-prefix
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config:
      as_number: "{{ bgp_asn }}"
      neighbors:
        - neighbor_address: "{{ hostvars[item]['rid_ip'] }}"
          address_family:
            - afi: l2vpn
              safi: evpn
              send_community:
                both: true
              rewrite_evpn_rt_asn: true
    state: merged
  when:
    - hostvars[item]['network_function'] == 'border-leaf'
    - hostvars[item]['bgp_asn'] != bgp_asn
  loop: "{{ bgp_neighbors }}"
  loop_control:
    label: BGP neighbor {{ hostvars[item]['inventory_hostname'] }}
  notify: Save nxos

- name: Advertise PIP in BGP process.  # For vPC.
  cisco.nxos.nxos_bgp_address_family:
    config:
      address_family:
        - afi: l2vpn
          safi: evpn
          advertise_pip: true
    state: merged
  notify: Save nxos

- name: Advertise virtual-rmac in NVE interface.  # For vPC.
  cisco.nxos.nxos_config:
    lines:
      - advertise virtual-rmac  # Enter shutdown, no shutdown to take effect
    parents:
      - interface nve1
  notify: Save nxos

- name: Ensure dci-tracking on fabric-external interfaces.
  # noqa loop-var-prefix
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.name }}"
        evpn_multisite_tracking: dci-tracking
    state: merged
  loop: "{{ dci_interfaces }}"
  loop_control:
    label: Interface {{ item.name }}
  notify: Save nxos

- name: Ensure fabric-tracking on fabric-internal interfaces.
  # noqa loop-var-prefix
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.name }}"
        evpn_multisite_tracking: fabric-tracking
    state: merged
  when: "'ethernet' in item.name | lower"
  loop: "{{ fabric_interfaces }}"
  loop_control:
    label: Interface {{ item.name }}
  notify: Save nxos

- name: Ensure EVPN multisite storm suppression for DCI interfaces.
  # noqa loop-var-prefix
  cisco.nxos.nxos_config:
    lines:
      - evpn storm-control {{ item }} level 5
  loop:
    - unicast
    - multicast
    - broadcast
  notify: Save nxos
