---
# tasks file for vxlan_evpn_fabric

- name: Enable MACsec features.
  # noqa no-loop-var-prefix
  cisco.nxos.nxos_feature:
    feature: macsec
    state: enabled
  notify: Save nxos

- name: Configure MACsec keychain and key.
  # noqa no-loop-var-prefix
  cisco.nxos.nxos_command:
    commands:
      - "{{ item }}"
  loop:
    - configure terminal
    - key chain 1 macsec
    - key 1000
    - key-octet-string {{ macsec_key }} cryptographic-algorithm AES_256_CMAC
  no_log: true
  notify: Save nxos

- name: Apply MACsec policy to DCI-interfaces.
  # noqa no-loop-var-prefix
  cisco.nxos.nxos_config:
    lines:
      - macsec keychain 1 policy system-default-macsec-policy
    parents:
      - interface {{ item.name }}
  loop: "{{ dci_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  notify: Save nxos
