---
# tasks file for vxlan_evpn_fabric

- name: Verify fabric underlay.
  block:

    - name: Get OSPF neighbors.
      cisco.nxos.nxos_command:
        commands:
          - show ip ospf neighbors
      register: ospf_neighbors

    - name: Print info about OSPF.
      ansible.builtin.debug:
        msg:
          - Spines should be neighbor with all leafs.
      run_once: true

    - name: Print OSPF Neighbors.
      ansible.builtin.debug:
        msg:
          - show ip ospf neighbors
          - "{{ ospf_neighbors['stdout_lines'][0] }}"

    - name: Get PIM neighbors.
      cisco.nxos.nxos_command:
        commands:
          - show ip pim neighbor
      register: pim_neighbors

    - name: Print info about PIM.
      ansible.builtin.debug:
        msg:
          - Spines should be neighbor with all leafs.
      run_once: true

    - name: Print PIM Neighbors.
      ansible.builtin.debug:
        msg:
          - show ip pim neighbor
          - "{{ pim_neighbors['stdout_lines'][0] }}"


- name: Verify fabric overlay.
  block:

    - name: Get NVE Peers.
      cisco.nxos.nxos_command:
        commands:
          - show nve peers
      register: nve_peers
      when: network_function in ['leaf', 'border-leaf']

    - name: Print info about NVE peers.
      ansible.builtin.debug:
        msg:
          - You will not see any peers before hosts-traffic has been initiated between peers.
      run_once: true
      when: network_function in ['leaf', 'border-leaf']

    - name: Print NVE Peers.
      ansible.builtin.debug:
        msg:
          - show nve peers
          - "{{ nve_peers['stdout_lines'][0] }}"
      when: network_function in ['leaf', 'border-leaf']


    - name: Get EVPN BGP neigbors.
      cisco.nxos.nxos_command:
        commands:
          - show bgp l2vpn evpn summary
      register: evpn_bgp_neighbors

    - name: Print info about EVPN BGP neighbors.
      ansible.builtin.debug:
        msg:
          - Spine (RR) should see all leafs as neighbors.
          - Border-leafs should also see remote border-leafs in separate BGP AS as neighbors.
      run_once: true

    - name: Print EVPN BGP neighbors.
      ansible.builtin.debug:
        msg:
          - show bgp l2vpn evpn summary
          - "{{ evpn_bgp_neighbors['stdout_lines'][0] }}"


- name: Verify the VXLAN configuration.
  when: network_function in ['leaf', 'border-leaf']
  block:

    - name: Print information about the next task.
      ansible.builtin.debug:
        msg:
          - Next task is run VXLAN config-check.
          - Timeout is 60 seconds.
      run_once: true

    - name: Run VXLAN config-check.
      cisco.nxos.nxos_command:
        commands:
          - show consistency-checker vxlan config-check
      register: config_check
      vars:
        ansible_command_timeout: 60

    - name: Print VXLAN config-check.
      ansible.builtin.debug:
        msg:
          - show consistency-checker vxlan config-check
          - "{{ config_check['stdout_lines'][0] }}"
