---
# tasks file for vxlan_evpn_fabric

- name: Assert that ansible_network_os is cisco.nxos.nxos.
  tags: always
  ansible.builtin.assert:
    that: ansible_network_os == 'cisco.nxos.nxos'
    msg: ansible_network_os must be cisco.nxos.nxos
    quiet: true

- name: Include variables.
  tags: always
  ansible.builtin.include_vars:
    file: "{{ network_function }}.yml"

- name: Enable features.
  # noqa loop-var-prefix
  tags: fabric_underlay, fabric_overlay
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"
    state: enabled
  loop: "{{ features }}"


- name: Configure fabric underlay.
  tags: fabric_underlay
  ansible.builtin.include_tasks:
    file: 01_underlay.yml
    apply:
      tags: fabric_underlay

- name: Configure fabric overlay.
  tags: fabric_overlay
  ansible.builtin.include_tasks:
    file: 02_overlay.yml
    apply:
      tags: fabric_overlay


- name: Configure DCI.
  when: network_function == 'border-leaf'
  block:

    - name: Configure DCI underlay.
      tags: dci_underlay
      ansible.builtin.include_tasks:
        file: 03_dci_underlay.yml
        apply:
          tags: dci_underlay

    - name: Configure DCI overlay.
      tags: dci_overlay
      ansible.builtin.include_tasks:
        file: 04_dci_overlay.yml
        apply:
          tags: dci_overlay

    - name: Configure DCI encryption.
      tags: dci_encryption
      ansible.builtin.include_tasks:
        file: 05_dci_encryption.yml
        apply:
          tags: dci_encryption


- name: Add host-segments to VTEPs.
  when: network_function in ['leaf', 'border-leaf']
  block:

    - name: Configure VRF.
      tags: vrf
      ansible.builtin.include_tasks:
        file: 06_vrf.yml
        apply:
          tags: vrf

    - name: Configure host segments with distributed anycast gateway.
      tags: l3
      ansible.builtin.include_tasks:
        file: 07_host_segments_l3.yml
        apply:
          tags: l3

    - name: Configure host segments without distributed anycast gateway.
      tags: l2
      ansible.builtin.include_tasks:
        file: 07_host_segments_l2.yml
        apply:
          tags: l2


- name: Verify fabric.
  tags: verify
  ansible.builtin.include_tasks:
    file: 08_verify_fabric.yml
    apply:
      tags: verify
